### ISSUE TITLE
Item ID not working

### ISSUE THREAD

**Issue by CXgraphics1** [disepi/ambrosial#112]
There is a few items I've come across that I cannot get to work with the ".give" command. 

One of the items is the different types of coral. Example ".give horn_coral 1" returns an item not found error
".give coral 1" will give tube coral, but none others work

A possible fix for this would be to add a file with all items and their id's to the ambrosial launcher

**Comment by brunoman4006** [comment]
verify if you have the correct id name
example: `.give <item> [amount]` this should work with anything on the game, including addons (it worked for me with some armor and swords addon, to obtain the stuff from addons the command is like this: `.give <source:item> [amount]`
where source can be either the mod tag or minecraft

however, there are some things that now have its own id name 

instead of `.give spawn_egg 1 [number about the mob id]´ it now are by separate names, 
´.give villager_spawn_egg 1`
`.give creeper_spawn_egg 65`
`.give spider_spawn_egg 32`

and about the file thing; if they add a file with all the items it could be better to be using the minecraft integrated files, and showing them while typing the command as the ´/give´ command

(i dunno if i could explain it well so hope its understandable)

**Comment by jawdropper16** [comment]
try adding another number like this .give coral 1 4

I might give you a diff coral depending how much types there are if there are 6 types try doing 1-6 to get the coral you want.
thats how it worked on horion for me.
