### ISSUE TITLE
Zephyr/Ambrosial wont inject if i press ,,inject". 

### ISSUE THREAD

**Issue by AlexOn240fps** [disepi/ambrosial#197]
i tried everything. turned off antivirus. waited for new update. installed visuals c++.  run at adminstrator. i updated windows and more... does net framework 4.7.2 not work on windows 11? it says ,,net framework or a later update is installed on this computer´´. im 96% sure i dont have 4.7.2 installed. i also put zephyr in an extra folder.

**Comment by danglezsdadad** [comment]
you have to wait until the creator updates the issue, nothing works for me especially with injecting so keep eyes on the updates for zephyr because the creator could launch a version. the reason it isnt working is because the creator of zephyr hasnt updated zephyr. there is basically nothing you can do but wait for the creator of zephyr to update the version of the ambrosial, this problem is also happening to me so no worrys. the reason this isnt occuring for you but working for everybody else is because they downloaded zephyr before minecraft updated its version to 1.19.63 but we just need to wait.

**Comment by Humii5592** [comment]
try now
