### ISSUE TITLE
Pressing Inject with MC Open does nothing?

### ISSUE THREAD

**Issue by TenCommands** [disepi/ambrosial#40]
The Injector doesn't work. :/

**Comment by bruhers** [comment]
same

**Comment by disepi** [comment]
Some modifications require the Visual C++ Redistributable (specifically x64). You can download this [here](https://aka.ms/vs/17/release/vc_redist.x64.exe). You may also need to download a more recent version of .NET Framework for Ambrosial itself. Another possible reason of injection not working is any antivirus software running that may interfere with the process because it may deem it malicious, in this case you will need to temporarily disable the software.
