### ISSUE TITLE
1.18.12 Zephyr Classic Launch Not Working

### ISSUE THREAD

**Issue by aternos24** [disepi/ambrosial#71]
My version is 1.18.12 and whenever I launch Zephyr Classic nothing will show up I'll attach a video

https://user-images.githubusercontent.com/78685482/166847166-8b477066-3537-4dfb-8f8f-b075cefe5424.mp4

.

**Comment by disepi** [comment]
Try installing Visual C++ x64 redist (https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by aternos24** [comment]
It's still not working.

**Comment by disepi** [comment]
Try press the folder button in the bottom left corner and delete the folder that pops up in the File Explorer window and try launch after that

**Comment by aternos24** [comment]
There's 2 folders do I delete both of them?

**Comment by aternos24** [comment]
Alright, here's what I did I deleted the Zephyr Classic folder and tried to inject/launch, after that It's still not working

**Comment by disepi** [comment]
There are many reasons why this may occur, there are fixes (ordered in severity) such as:

## 1 - Checking the game's version
If your game is force closing, make sure your **local version** (located at the bottom-left of the Ambrosial launcher's main page) matches to the **version of the modification you are launching** (located below the modification's name on the modification's page).

## 2 - Installing Visual C++ Redistributable
The redistributable can be found [here](https://aka.ms/vs/17/release/vc_redist.x64.exe). After installation, the client you are injecting should work as expected.

## 3 - Clearing client download cache
This can be done by entering the modification's page in Ambrosial, clicking the folder button in the bottom left and deleting the version folders (numbered folders). This issue will fix corrupted downloads.

## 4 - Ensuring you have a stable internet connection
Ambrosial requires a stable active internet connection in order to operate. Please ensure your internet provider has no current downtime or outage and that your connection is stable. Once you have completed this, follow the step above. If you wish to use Ambrosial or any included modification without an internet connection, you must first launch it with an internet connection first.

## 5 - Disabling your antivirus
It may not seem necessary to, but your antivirus can stop the launch process in many ways such as stopping the client download, stopping creation of files in relation to the client and stopping Ambrosial from accessing your game instance. Disabling these antivirus measures will allow the launcher to complete its tasks as expected. Please search up instructions from your antivirus provider on how to disable these measures. If you do not have an antivirus installed, try disable Windows Security.

## 6  - Checking your games target architecture
Ambrosial and most included modifications are designed to operate on the x64 Minecraft: Windows 10 executable. Unexpected results may occur on any other version. If you are on a 64-bit system, reinstall your game using Microsoft Store or any external program that provides the x64 build of the game. If you are on a 32-bit system, please look at the last step.

## 7 - Installing correct .NET Framework
In some instances, you may be missing the .NET Framework which Ambrosial requires. Ambrosial may alert you of this by refusing to launch and or giving you a launch alert about this. There are many causes of this, some examples are having an older version of the framework installed, having an older version of Windows that does not come packaged with the framework and accidental uninstallation of it. The download for the required .NET Framework can be found [here](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net472-web-installer).

## 8 - Upgrading your Windows
This is usually a last resort. Ambrosial does not support 32-bit systems and if you wish to use it then you must upgrade your system. You can obtain your OS architecture on Windows 10 by opening the "Settings" app, choosing the "System" category and choosing the "About" tab. Your architecture will be listed under the "Device specifications" header in the "System Type" index. If your textbox reads "**32-bit operating system, x64-based processor**" then you are eligible for an x64 operating system upgrade and you should search up how to proceed to do so. If it reads "**x32-based processor**", you **will** need to upgrade your CPU and OS to a x64 architecture in order to proceed. Ambrosial may also produce unexpected results on Windows versions below 1909/19H2.


**You do not have to complete some of these fixes if you do not wish to, although it is recommended to do so in order to setup the right environment for Ambrosial to operate in.**

If you have any other problem, feel free to open another issue on this GitHub page.

**Comment by aternos24** [comment]
It's fixed some since the new update on ambrosial. thanks
