### ISSUE TITLE
Virustotal flags ambrosial latest release as malicious.

### ISSUE THREAD

**Issue by Ultra-max99** [disepi/ambrosial#81]
If it is flagged, shouldn't it be flagged as an injector? It looks like it is being flagged as Ransomware and a Trojan, although some are Injectors.
![virustotal](https://user-images.githubusercontent.com/80412399/177216505-5906aa44-4138-4ec3-9165-36f5971cdef2.png)
https://www.virustotal.com/gui/file/6ff53b8187d0d3e287ad9ce3da20eca4f9dd105a2e3421ca1ad73b533ec4b91a

**Comment by disepi** [comment]
This is most likely because Ambrosial uses downloads files (for modifications) which can be perceived by antiviruses as "malicious". This is the same with the DLL injection, opening of executables, creating files, automatic font installation and more, which is all used in the purpose of installing modifications to Minecraft.

Also, take note that most of the antiviruses displayed that are displayed which detecting malware aren't really known at all and can't be trusted that much. There is an exception with this for Malwarebytes, although they do have very strict detection checks so it doesn't surprise me that it did detect Ambrosial as malicious.

I can't really do anything about this since it is not my problem that antiviruses are not doing their job properly, if I were to take action and remove the code that is deemed "malicious", I would have to remove vital parts that would remove the purpose of the launcher itself.

Also take note that Ambrosial is open source and that all the release executables are uploaded straight from compiled source and don't have any obfuscation in place. Nothing is stopping you from running it on a virtual machine, debugging it, decompiling it, etc.
